name: GDExtension CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux GCC
            compiler_c: gcc
            compiler_cxx: g++
            build_type: Debug
          - os: windows-latest
            name: Windows MSVC
            compiler_c: cl
            compiler_cxx: cl
            build_type: Debug
          - os: macos-latest
            name: macOS Clang
            compiler_c: clang
            compiler_cxx: clang++
            build_type: Debug

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install scons
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then
            brew install scons molten-vk
          else
            pip3 install scons
          fi
        shell: bash

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/.out
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler_cxx }}
          -DCMAKE_C_COMPILER=${{ matrix.compiler_c }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}
          -G Ninja

      - name: Build
        run: cmake --build ${{ github.workspace }}/.out --config ${{ matrix.build_type }} --target roguelite --parallel
