name: GDExtension CMake

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: "[linux | gcc] => cmake - configure"
        run: >
          cmake -B ${{ github.workspace }}/.out
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Debug
          -S ${{ github.workspace }}
          -G Ninja
      - name: "[linux | gcc] => cmake - build"
        run: cmake --build ${{ github.workspace }}/.out --config Debug --target roguelite --parallel 48
